import type { Exercice } from '@/types';

// ========== TOUS LES EXERCICES DE CALYPSO ==========
// Repris exactement de la base de données actuelle
export const MOCK_EXERCICES: Exercice[] = [
  // ==================== BAS DU CORPS (Jambes, Bassin, Pied) ====================
  {
    id: 1,
    name: "Papillon",
    description: {
      text: "Sur le dos, genoux écartés. On écarte les deux genoux vers droite et gauche.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Lit"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: true,
    completedAt: new Date(),
    pinned: true,
  },
  {
    id: 2,
    name: "Torsion",
    description: {
      text: "Sur le dos, genoux ensemble. Droite et gauche.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Lit"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 3,
    name: "Montée de genoux",
    description: {
      text: "Allongée, montée de genoux vers la poitrine, alterner droite et gauche.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Lit"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 4,
    name: "Assis / Debout",
    description: {
      text: "Descendre très lentement.",
      comment: "Renforce les cuisses.",
    },
    workout: { repeat: '10', series: '4', duration: null },
    equipments: ["Chaise"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: true,
    completedAt: new Date(),
    pinned: true,
  },
  {
    id: 5,
    name: "Escaliers",
    description: {
      text: "Monter et descendre les escaliers sur un étage.",
      comment: "Bonus: Tout faire avec le côté droit.",
    },
    workout: { repeat: '2', series: '1', duration: null },
    equipments: ["Escaliers"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 6,
    name: "Equilibre sur une jambe",
    description: {
      text: "Tenir l'équilibre sur une jambe.",
      comment: "Se tenir si nécessaire.",
    },
    workout: { repeat: '1', series: '1', duration: "30 secondes chaque jambe" },
    equipments: [],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 7,
    name: "Levée de genoux",
    description: {
      text: "Debout à côté d'une porte, lever le genou et tenir. Alterner.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: "30 secondes" },
    equipments: ["Porte"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 8,
    name: "Montée et descente de genoux",
    description: {
      text: "Debout à côté d'une porte, montée et descente de genoux, alterner droit et gauche. Puis, 10x coups de pieds vers l'arrière, 10x coups de pieds vers le côté (jambe tendue).",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Porte"],
    bodyparts: ["Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 9,
    name: "Le pont",
    description: {
      text: "Décoller fesses du lit, genoux pliés.",
      comment: "Serrer les fessiers en haut.",
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Lit"],
    bodyparts: ["Bassin"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 10,
    name: "Pont avec levée de jambe",
    description: {
      text: "En position de pont, lever une jambe tendue. Alterner.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Lit"],
    bodyparts: ["Bassin", "Jambes"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 11,
    name: "Squat accrochée au balcon",
    description: {
      text: "Squat accrochée au balcon. 70% jambes, 30% bras. Descendre le plus bas possible.",
      comment: "Rechercher l'échec.",
    },
    workout: { repeat: '10', series: '1', duration: "90 secondes" },
    equipments: ["Rambarde"],
    bodyparts: ["Dos", "Fessier"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 12,
    name: "Pliage cheville",
    description: {
      text: "Plier et déplier les chevilles, pointe vers le haut puis vers le bas.",
      comment: "Améliore la mobilité des chevilles.",
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Pied"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 13,
    name: "Pliage cheville face bibliothèque",
    description: {
      text: "Pliage de cheville en position debout face à la bibliothèque pour se tenir.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Pied"],
    category: "LOWER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },

  // ==================== HAUT DU CORPS (Bras, Mains, Épaules, Dos) ====================
  {
    id: 14,
    name: "Levée de bâton (paume vers le bas)",
    description: {
      text: "Les deux mains attrapent le bâton au milieu et le lèvent le plus haut possible.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Bâton"],
    bodyparts: ["Bras"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 15,
    name: "Levée de bâton (paume vers le haut)",
    description: {
      text: "Les deux mains attrapent le bâton au milieu et le lèvent vers la poitrine en pliant les coudes.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Bâton"],
    bodyparts: ["Bras"],
    category: "UPPER_BODY",
    completed: true,
    completedAt: new Date(),
    pinned: false,
  },
  {
    id: 16,
    name: "Pompes accrochée au balcon",
    description: {
      text: "Pompes bras inclinés sur la rambarde.",
      comment: "Plus on recule, plus c'est difficile.",
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Rambarde"],
    bodyparts: ["Dos", "Bras"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 17,
    name: "Pliage du coude",
    description: {
      text: "Allongée, plier le coude et déplier tout doucement en forçant sur l'extension.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Lit"],
    bodyparts: ["Bras"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 18,
    name: "Levée le bras - horizon",
    description: {
      text: "Lever le bras tendu jusqu'à l'horizontale et maintenir 2 secondes.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: "2 secondes" },
    equipments: [],
    bodyparts: ["Bras"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 19,
    name: "Ramener bras tendu avec sangle",
    description: {
      text: "Avec la sangle, ramener le bras tendu vers soi.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: ["Sangle"],
    bodyparts: ["Bras"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 20,
    name: "Pliage bras debout",
    description: {
      text: "Debout, plier et déplier les bras.",
      comment: null,
    },
    workout: { repeat: '5', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Bras"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 21,
    name: "Ouvrir et fermer la main",
    description: {
      text: "Serrer la main puis l'ouvrir et la relâcher.",
      comment: "Améliore la force de préhension.",
    },
    workout: { repeat: '30', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Mains"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: true,
  },
  {
    id: 22,
    name: "Montée d'épaules",
    description: {
      text: "Monter la pointe des épaules vers les oreilles le plus haut possible.",
      comment: null,
    },
    workout: { repeat: '10', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Épaules"],
    category: "UPPER_BODY",
    completed: false,
    completedAt: null,
    pinned: false,
  },

  // ==================== ÉTIREMENTS ====================
  {
    id: 23,
    name: "Etirer les bras",
    description: {
      text: "Attraper une rambarde et reculer les pieds, se pencher en avant. Compter jusqu'à 100.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: null },
    equipments: ["Rambarde"],
    bodyparts: ["Bras"],
    category: "STRETCHING",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 24,
    name: "Étirement bras horizon avec sangle",
    description: {
      text: "Étirer le bras à l'horizontale avec l'aide de la sangle.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: "30 secondes" },
    equipments: ["Sangle"],
    bodyparts: ["Bras"],
    category: "STRETCHING",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 25,
    name: "Etirer la main",
    description: {
      text: "Étirer la main vers l'arrière.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: "90 secondes" },
    equipments: [],
    bodyparts: ["Mains"],
    category: "STRETCHING",
    completed: true,
    completedAt: new Date(),
    pinned: true,
  },
  {
    id: 26,
    name: "Etirer la main sur la table",
    description: {
      text: "Étirer la main vers l'arrière sur la table, bras tendu.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: "90 secondes" },
    equipments: ["Table"],
    bodyparts: ["Mains", "Bras"],
    category: "STRETCHING",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 27,
    name: "Etirement des doigts",
    description: {
      text: "Orienter les doigts vers la cuisse, tendre le bras et étirer pendant 2 minutes.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: "120 secondes" },
    equipments: [],
    bodyparts: ["Mains"],
    category: "STRETCHING",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 28,
    name: "Inclinaison de la tête",
    description: {
      text: "Tourner et incliner la tête vers la gauche, puis vers la droite.",
      comment: null,
    },
    workout: { repeat: '1', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Nuque / Cervicales", "Épaules"],
    category: "STRETCHING",
    completed: false,
    completedAt: null,
    pinned: false,
  },
  {
    id: 29,
    name: "Etirement de la nuque",
    description: {
      text: "Avec la main gauche, attraper la tempe droite et pencher la tête et RESPIRER.",
      comment: "Très important de bien respirer.",
    },
    workout: { repeat: '1', series: '1', duration: null },
    equipments: [],
    bodyparts: ["Nuque / Cervicales"],
    category: "STRETCHING",
    completed: false,
    completedAt: null,
    pinned: false,
  },
];

// Mode démo - mettre à false pour utiliser la vraie base de données
// Mettre à true pour utiliser les données fictives, false pour la base Neon
export const USE_MOCK_DATA = false;
