import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/components/organisms/NavBar";
import SiteProtection from "@/app/components/organisms/SiteProtection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <SiteProtection>
          <NavBar />
          <main className="flex-1 mx-auto min-h-screen h-full w-full max-w-9xl">
              {children}
          </main>
        </SiteProtection>
      </body>
    </html>
  );
}
