import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/organisms/Sidebar";
import UpBar from "@/app/components/organisms/UpBar";
import SiteProtection from "@/app/components/organisms/SiteProtection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={` antialiased flex`}
      >
        <SiteProtection>
          <Sidebar />
          <main className="flex-1 mx-auto min-h-screen max-h-screen overflow-auto">
            <div className="flex-1">
              <UpBar />
          
              
              {children}
            </div>
          </main>
        </SiteProtection>
      </body>
    </html>
  );
}
